### ISSUE TITLE
CI/CD 專案編譯時間優化

### ISSUE THREAD

**Issue by sageofcross** [sageofcross/just-note-it#3]
## 背景
當時 API Gateway 使用 Scala 語言開發，幾乎不管哪個功能都一定得跟它打交道，然而 GitLab CI/CD 編譯實在太久（最少 20 分鐘起跳），讓這個梗圖不再只是梗：

![xkcd-compiling](https://github.com/user-attachments/assets/1f2990f9-8856-4134-a108-59d99f2e2e81)

## 問題
雖然此專案存在已久，但有趣的是團隊內對 Scala 真正熟的人可以說幾乎沒有，也從沒有人想試著優化。

而我就是那個受不了自己跳下去的人。

### 第一步
先從編譯核心開始，專案狀態為：

- 編譯版本： Scala v2.12.6
- 建構工具： sbt 1.2.8

查詢了一下 sbt ，發現在 [v1.3.0](https://github.com/sbt/sbt/releases/tag/v1.3.0) 時改用 Coursier 來管理依賴（原本為 Ivy ），最重要的是支援平行下載套件；編譯版本則影響了性能與檔案大小，所以我豪不猶豫的選擇升級。

只靠升級我 Local 編譯速度就省了約 30s ，雖然杯水車薪但這麼簡單的調整就能加速還是很意外。

> Scala 直升 2.13 時編譯會碰到問題，改走保守路線選 2.12 最新版

### 第二步
多數編譯語言加速的原理就是重複使用已編譯的結果，只對有變動的部分重新處理，白話點：「用快取」。

GitLab Runner 有提供快取機制，因此接著就分析了 sbt 建構時如何利用快取，發現以下幾個目錄：

| 目錄 | 用途 |
| --: | :-- |
| sbt global base | 全域設定與 Plugins |
| sbt root | 共享的 sbt boot 內容 |
| cousier cache | 依賴管理核心，依賴的檔案都存在這裡面 |
| ivy cache | 早期 sbt 的依賴目錄，理論上有 Cousier 後就不需要，但觀察時發現裡面還是有些套件資料 |

根據這些資訊，對 CI/CD 設定做了調整：

```yaml
build-tarball:
  ...
  # 設定相關的 sbt 參數，便於後面快取
  variables:
      SBT_OPTS: "-Dsbt.global.base=${CI_PROJECT_DIR}/.sbt -Dsbt.boot.directory=${CI_PROJECT_DIR}/.boot -Dsbt.coursier.home=${CI_PROJECT_DIR}/.cache -Dsbt.ivy.home=${CI_PROJECT_DIR}/.ivy"
  ...
  cache:
    key: api-gateway-${CI_PROJECT_PATH_SLUG}
    untracked: true # 把所有不在 Git 內的檔案都快取起來
    # 對照上面的 sbt 參數目錄
    paths:
      - .sbt/
      - .boot/
      - .cache/
      - .ivy/
```

### 第三步
這個步驟算是多餘的。

當時想一併將專案使用的 Protobuf 程式碼生成做個整理，才發現有許多 API Gateway 不需要的目錄可以排除，多少省一點時間。

## 結果
編譯時間都能壓在 10 分鐘內，也就是耗時只需要原先的 50% ，誇張點的情況只要原本的 20% 。此外也縮小建立出來的 Image 大小，縮到原始的 60% 左右。

我們的 API Gateway 有分對外與對內部兩組，各自的結果可參考附圖。

### 主要 API Gateway （對外）
編譯速度提升：
![速度為原始的 20%](https://github.com/user-attachments/assets/ad8f8966-217d-4ae9-b2da-0d4a62e6b135)

Image 縮小：
![Image](https://github.com/user-attachments/assets/2b0ba85c-0c25-43c6-826a-94ae212c834d)

### 次要 API Gateway （對內）
編譯速度提升：
![Image](https://github.com/user-attachments/assets/52ea3de6-983c-4aa6-86a8-3a4f017acd9f)

Image 縮小：
![Image](https://github.com/user-attachments/assets/05aefcc6-2bc0-48ce-a815-31e393f75a73)

## 結論
做過一次後就知道原理很單純，也是大多數 CI/CD 工具都支援的做法，可能會需要考慮的是快取內容的管理，例如：

- 是否得安排過期（ TTL ）
- 快取有沒有可能過大
- 不同 MR 之間能否共用

但我想這些應該都不難找到 Best Praatice ，就是得花點時間檢驗而已。
